id: P007845
initial_creation_type: ocr
source_metadata:
  id: bdr:W22111
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ་།（བཀྲས་ལྷུན་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  volumes:
    7e467606f70e4fdcac1e5aced6b9627e:
      image_group_id: I00KG03901
      title: ''
      volume_number: 1
      total_pages: 488
    e53eabc13e634df184780f3f52d2d1f0:
      image_group_id: I00KG03902
      title: ''
      volume_number: 2
      total_pages: 448
    c2e620edf02e4d32aaf664d21c4379ab:
      image_group_id: I00KG03903
      title: ''
      volume_number: 3
      total_pages: 700
    1ff22a7f3e84445aa3fc3586ee53e979:
      image_group_id: I00KG03904
      title: ''
      volume_number: 4
      total_pages: 534
    e11e4be0e44a46e086e9b5b59ab340fe:
      image_group_id: I00KG03905
      title: ''
      volume_number: 5
      total_pages: 632
    b3d281dbe6d44df29b5dc25b214b1b51:
      image_group_id: I00KG03906
      title: ''
      volume_number: 6
      total_pages: 470
    bbc7a41d37ff4a57946b5fc34e3fe686:
      image_group_id: I00KG03907
      title: ''
      volume_number: 7
      total_pages: 456
    050f34e3889c482c843dab98eaaae8eb:
      image_group_id: I00KG03908
      title: ''
      volume_number: 8
      total_pages: 562
    685cdd76eace443787e06f717f2c3bc1:
      image_group_id: I00KG03909
      title: ''
      volume_number: 9
      total_pages: 638
    5ec95bee8e4f493eafa26c443d233ebd:
      image_group_id: I00KG03910
      title: ''
      volume_number: 10
      total_pages: 638
    4179c9c9796943f6ad2e42edc90670a4:
      image_group_id: I00KG03911
      title: ''
      volume_number: 11
      total_pages: 670
    fa9362185bb84029b80aedf27cc65b15:
      image_group_id: I00KG03912
      title: ''
      volume_number: 12
      total_pages: 690
ebook_metadata:
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ་།（བཀྲས་ལྷུན་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  sku: P007845
  cover: cover.jpg
  layers:
  - pagination
