id: I1E512E42
legacy_id: P007845
ocr_import_info:
  bdrc_scan_id: W22111
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T18:37:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:35:51.023703+00:00'
last_modified: 2022-09-02 04:41:35.457550
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22111
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22111
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ་།（བཀྲས་ལྷུན་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: མཁས་གྲུབ་རྗེ་དགེ་ལེགས་དཔལ་བཟང་།
statistics:
  ocr_word_mean_confidence_index: 0.7238616860403025
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I00KG03904:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03904
      total_pages: 534
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00KG03904.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7324100253132891
    legacy_id: v004
  I00KG03909:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03909
      total_pages: 638
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I00KG03909.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7165859731471816
    legacy_id: v009
  I00KG03912:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03912
      total_pages: 690
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I00KG03912.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6274717328803173
    legacy_id: v012
  I00KG03903:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03903
      total_pages: 700
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00KG03903.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.71809883786993
    legacy_id: v003
  I00KG03907:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03907
      total_pages: 456
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I00KG03907.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7539983582877727
    legacy_id: v007
  I00KG03905:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03905
      total_pages: 632
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00KG03905.txt
    statistics:
      ocr_word_median_confidence_index: 0.8199999928474426
      ocr_word_mean_confidence_index: 0.7572158447433059
    legacy_id: v005
  I00KG03908:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03908
      total_pages: 562
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I00KG03908.txt
    statistics:
      ocr_word_median_confidence_index: 0.75
      ocr_word_mean_confidence_index: 0.703286195259124
    legacy_id: v008
  I00KG03911:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03911
      total_pages: 670
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I00KG03911.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7413545314553727
    legacy_id: v011
  I00KG03902:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03902
      total_pages: 448
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00KG03902.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7431938638536877
    legacy_id: v002
  I00KG03906:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03906
      total_pages: 470
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I00KG03906.txt
    statistics:
      ocr_word_median_confidence_index: 0.8100000023841858
      ocr_word_mean_confidence_index: 0.7527511874372694
    legacy_id: v006
  I00KG03910:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03910
      total_pages: 638
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I00KG03910.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.7092928100576956
    legacy_id: v010
  I00KG03901:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG03901
      total_pages: 488
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG03901.txt
    statistics:
      ocr_word_median_confidence_index: 0.800000011920929
      ocr_word_mean_confidence_index: 0.7425155097710192
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
