id: I1E512E42
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T18:45:41+00:00'
last_modified: '2022-06-09T06:31:09.170471+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22111
  title: གསུང་འབུམ། མཁས་གྲུབ་རྗེ་།（བཀྲས་ལྷུན་པར་མ། ལྡི་ལིར་བསྐྱར་པར་བརྒྱབ་པ།）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    54EA:
      image_group_id: I00KG03901
      title: Volume 1 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 488
      order: 1
      base_file: 54EA.txt
    576D:
      image_group_id: I00KG03902
      title: Volume 2 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 448
      order: 2
      base_file: 576D.txt
    BB77:
      image_group_id: I00KG03903
      title: Volume 3 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 700
      order: 3
      base_file: BB77.txt
    6D9D:
      image_group_id: I00KG03904
      title: Volume 4 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 534
      order: 4
      base_file: 6D9D.txt
    F4BF:
      image_group_id: I00KG03905
      title: Volume 5 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 632
      order: 5
      base_file: F4BF.txt
    '4865':
      image_group_id: I00KG03906
      title: Volume 6 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 470
      order: 6
      base_file: 4865.txt
    B0B2:
      image_group_id: I00KG03907
      title: Volume 7 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 456
      order: 7
      base_file: B0B2.txt
    B3BB:
      image_group_id: I00KG03908
      title: Volume 8 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 562
      order: 8
      base_file: B3BB.txt
    '9839':
      image_group_id: I00KG03909
      title: Volume 9 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 638
      order: 9
      base_file: 9839.txt
    E0AB:
      image_group_id: I00KG03910
      title: Volume 10 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 638
      order: 10
      base_file: E0AB.txt
    4D94:
      image_group_id: I00KG03911
      title: Volume 11 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 670
      order: 11
      base_file: 4D94.txt
    5C1E:
      image_group_id: I00KG03912
      title: Volume 12 of gsung 'bum/_mkhas grub rje (gelek)
      total_pages: 690
      order: 12
      base_file: 5C1E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
